### ISSUE TITLE
Add a periodic timer flavor

### ISSUE THREAD

**Issue by llucax** [llucax/pausable_timer#45]
There has been already a couple of requests for an easy way to create a pausable periodic timer in #19.

People seems to expect a `PausableTimer.periodic()` constructor, even when it's trivial to build on top of `PausableTimer` bacause it trivial to reset it and start it again.

Example:

```dart
timer = PausableTimer(
    Duration(seconds: 1),
    () {
      // This is really what your callback do.
      print('A period has passed');

      // we know the callback won't be called before the constructor ends, so
      // it is safe to use !
      timer
        ..reset()
        ..start();
    },
  )..start();
```

Once you want your timer to go away, you can just `.pause()` it and that's it. There is the caveat that if the actual work your callback does takes too long, the period will stretch. If you reset the timer before doing the actual work, it can be called without any further wait if it took longer than the period. Finally the time it takes for the work to be done can be calculated and the duration of the timer adjusted accordingly, which gets much less trivial, so maybe it is a worthy addition anyway :thinking:

**Comment by mateusfccp** [comment]
@llucax

I am currently implementing this feature, and initially I was trying to address the stretching issue. However, I did encounter this in [the documentation for Timer.periodic](https://api.dart.dev/stable/2.17.3/dart-async/Timer/Timer.periodic.html):

> The exact timing depends on the underlying timer implementation. No more than `n` callbacks will be made in `duration * n` time, but the time between two consecutive callbacks can be shorter and longer than `duration`.

Indeed, I tested with `Timer.periodic` and the stretching issue also occurs with it.

I have decided not to solve the problem. Instead, I am using `Zone.createPeriodicTimer` internally so that the behavior of the `PausableTimer` will be the same as that of the `Timer`.

This means that in platforms where time does not stretch, it won't stretch; in platforms where time stretches, it will stretch.

This way, we have consistent behavior between `Timer` and `PausableTimer`.
